### PR TITLE
Setup ORM, Database & Database Migration Files

### LINKED ISSUE #3: Database schema
We need to create the database schema for the project. This might need to be an RDBMS because of the person working on authentication.

### PR DESCRIPTION
**Pull request by meetKazuki**
#### What does this PR do?
* setup `MySQL` database connection.
* setup `sequelize` as ORM.
* setup database migration files and migration scripts.

#### Description of task to be completed?
Four new scripts have been added to `package.json`:
 - `db:migrate`: responsible for creating/tracking tables in our `MySQL` database,
 - `db:migrate:undo`:
 - `db:reset`: ,
 -  `db:seed`: ,

#### What are the relevant user stories?
closes #3

### CODE REVIEW

**Comment by Auwalms** [comment]
Hello @meetKazuki, there is a merge conflict on this PR, can you pull from develop and fix the merge conflict for us? I would ideally do this but I want to be sure I don't erroneously delete something. Thank you

**Comment by Auwalms** [comment]
Oh great, this is fixed. Reviewing and Merging now.

**Comment by Auwalms** [comment]
@meetKazuki You seems to have changed the folder structure from the initially agreed way of dividing the folders based on domain. A fellow contributor worked on that last night and it won't be great to just do away with it. Can we revert to the former folder structure?

**Comment by meetKazuki** [comment]
> @meetKazuki You seems to have changed the folder structure from the initially agreed way of dividing the folders based on domain. A fellow contributor worked on that last night and it won't be great to just do away with it. Can we revert to the former folder structure?

I will work on it. Sorry for the inconvenience.

**Comment by tag6071** [comment]
@meetKazuki Good Job implementing this, As mentioned by @Auwalms I think we should follow the DDD structure so we can have the functionality for the server structured according the domain of the problem we are trying to solve. 

Also, I think it would be good if we try to avoid deeply nested folders so it is easier to reach a file to be worked on.

So, from the schema below 👇 

Screenshot 2020-10-23 at 10 34 42

I think you might want to do some of these:
- change `contributors` to `users` (might need to confirm this, as I implemented this before with respect to the frontend issues please confirm @Auwalms @securetorobert) and add the database definition to `users/userModel`
- Add an `emailVerificationModel` to the `auth` folder
- create new domain folder for `accused` with its controllers and stuff then add `accusedModel` and `accusedOffencesModel` in there
- rename `cases/casesModel` to `cases/caseModel` and also add `caseUpdateModel` to the `cases` domain folder
- rename `victims/victimsModel` to `victims/victimModel`

So, the database definitions according to the schema can be added to these models, also you can leave `migrations` at the root of the project and move all ORM/database configs into the `database` folder.

**Pull request merged**
